// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GenericRequest is an autogenerated mock type for the GenericRequest type
type GenericRequest struct {
	mock.Mock
}

type mockConstructorTestingTNewGenericRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewGenericRequest creates a new instance of GenericRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGenericRequest(t mockConstructorTestingTNewGenericRequest) *GenericRequest {
	mock := &GenericRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
