// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/taxcode:calculate-person-data": {
            "post": {
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Calculate data of a person starting from his tax code.",
                "parameters": [
                    {
                        "description": "CalculatePersonDataRequest",
                        "name": "CalculatePersonDataRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CalculatePersonDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CalculatePersonDataResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/taxcode:calculate-tax-code": {
            "post": {
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Calculate tax code starting from the data of a person.",
                "parameters": [
                    {
                        "description": "CalculateTaxCodeRequest",
                        "name": "CalculateTaxCodeRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CalculateTaxCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CalculateTaxCodeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.CalculatePersonDataRequest": {
            "type": "object",
            "properties": {
                "taxCode": {
                    "type": "string"
                }
            }
        },
        "service.CalculatePersonDataResponse": {
            "type": "object",
            "properties": {
                "birthPlace": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "UNKNOWN",
                        "MALE",
                        "FEMALE"
                    ]
                },
                "name": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "taxCode": {
                    "type": "string"
                }
            }
        },
        "service.CalculateTaxCodeRequest": {
            "type": "object",
            "properties": {
                "birthPlace": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "UNKNOWN",
                        "MALE",
                        "FEMALE"
                    ]
                },
                "name": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "service.CalculateTaxCodeResponse": {
            "type": "object",
            "properties": {
                "taxCode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "taxcode-converter",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
